print("Hello World")

ans1 = input("Guess the coin flip. Press 'A' for heads or 'B' for tails")
if ans1 =("A")
    print("Loading...")
    print("Wrong it's tails")
elif ans1 =("B")
    print("Loading...")
    print("Correct it's tails")
    ans2 = input("Guess the coin flip. Press 'A' for heads or 'B' for tails")
    if ans2 =("A")
    print("Correct it's heads")
    print("Loading...")
    elif ans1 =("B")
    print("Loading...")
    print("Wrong it's tails")
